### PR TITLE
Fix crash in error pretty printer - Flow CLI (REPL)

### PR DESCRIPTION
**Pull request by Maelkum**
## Description

This PR makes a few code changes to the Cadence error pretty printer.

Since the crash is tightly coupled with the scenario of using a REPL that does somewhat unexpected things (like inserting empty code lines) adding tests would be somewhat more involved to custom tailor this scenario (but probably possible).

It's possible to test this quickly using https://github.com/Maelkum/cadence/tree/fix-pretty-print-v0.26.0 in a `replace` directive in `go.mod` file (I've got some errors trying to build Flow CLI with latest master of Cadence).

### Crash Description

Reproducible using latest Flow CLI (master branch) targeting Cadence v0.26.0 (also reproducible on v0.26.1).
Use Flow CLI to start Cadence REPL and try to re-declare a constant.

<details>
  <summary>Stack trace</summary>

```
./flow cadence
Welcome to Cadence v0.26.0!
Type '.help' for assistance.

1> let x = 1
2> let x = 1
error: cannot redeclare constant: `x` is already declared
 --> REPL:1:4
  |
1 |
  | panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/onflow/cadence/runtime/pretty.ErrorPrettyPrinter.PrettyPrintError.func1()
        /home/aco/go/pkg/mod/github.com/onflow/cadence@v0.26.0/runtime/pretty/print.go:156 +0x106
panic({0x178bc40, 0xc000044438})
        /usr/local/go/src/runtime/panic.go:838 +0x207
github.com/onflow/cadence/runtime/pretty.ErrorPrettyPrinter.writeCodeExcerpts({{0x1e42500?, 0xc000010020?}, 0xc2?}, {0xc0001e2f00, 0x2, 0x40e374?}, {0x1e51548, 0x2a39848}, {0xc0001443e0, 0xb})
        /home/aco/go/pkg/mod/github.com/onflow/cadence@v0.26.0/runtime/pretty/print.go:316 +0x7e5
github.com/onflow/cadence/runtime/pretty.ErrorPrettyPrinter.prettyPrintError({{0x1e42500?, 0xc000010020?}, 0x80?}, {0x1e37ca0?, 0xc00026c080}, {0x1e51548, 0x2a39848}, {0xc0001443e0, 0xb})
        /home/aco/go/pkg/mod/github.com/onflow/cadence@v0.26.0/runtime/pretty/print.go:238 +0x326
github.com/onflow/cadence/runtime/pretty.ErrorPrettyPrinter.PrettyPrintError.func2({0x1e37ca0, 0xc00026c080}, {0x1e51548, 0x2a39848})
        /home/aco/go/pkg/mod/github.com/onflow/cadence@v0.26.0/runtime/pretty/print.go:202 +0x1ba
github.com/onflow/cadence/runtime/pretty.ErrorPrettyPrinter.PrettyPrintError.func2({0x1e36ee0, 0xc00027c030}, {0x1e51548, 0x2a39848})
        /home/aco/go/pkg/mod/github.com/onflow/cadence@v0.26.0/runtime/pretty/print.go:189 +0x298
github.com/onflow/cadence/runtime/pretty.ErrorPrettyPrinter.PrettyPrintError({{0x1e42500?, 0xc000010020?}, 0x60?}, {0x1e36ee0, 0xc00027c030}, {0x1e51548?, 0x2a39848?}, 0xb24bed74f3876c01?)
        /home/aco/go/pkg/mod/github.com/onflow/cadence@v0.26.0/runtime/pretty/print.go:207 +0x12e
github.com/onflow/cadence/runtime/cmd/execute.RunREPL.func1({0x1e36ee0?, 0xc00027c030?}, {0x1e51548?, 0x2a39848?}, 0xc000632420?)
        /home/aco/go/pkg/mod/github.com/onflow/cadence@v0.26.0/runtime/cmd/execute/repl.go:46 +0x50
github.com/onflow/cadence/runtime.(*REPL).handleCheckerError(0xc00089f9e0?)
        /home/aco/go/pkg/mod/github.com/onflow/cadence@v0.26.0/runtime/repl.go:102 +0xc9
github.com/onflow/cadence/runtime.(*REPL).check(0xc00089f9e0, {0x1e4c360?, 0xc0001661a0?}, {0xc0001443e0, 0xb})
        /home/aco/go/pkg/mod/github.com/onflow/cadence@v0.26.0/runtime/repl.go:122 +0x99
github.com/onflow/cadence/runtime.(*REPL).Accept(0xc00089f9e0, {0xc0001443e0, 0xb})
        /home/aco/go/pkg/mod/github.com/onflow/cadence@v0.26.0/runtime/repl.go:156 +0x253
github.com/onflow/cadence/runtime/cmd/execute.RunREPL.func3({0xc000144293, 0x9})
        /home/aco/go/pkg/mod/github.com/onflow/cadence@v0.26.0/runtime/cmd/execute/repl.go:80 +0x1d7
github.com/c-bata/go-prompt.(*Prompt).Run(0xc000893050)
        /home/aco/go/pkg/mod/github.com/c-bata/go-prompt@v0.2.5/prompt.go:84 +0x745
github.com/onflow/cadence/runtime/cmd/execute.RunREPL()
        /home/aco/go/pkg/mod/github.com/onflow/cadence@v0.26.0/runtime/cmd/execute/repl.go:119 +0x2b7
github.com/onflow/flow-cli/internal/cadence.glob..func1(0x2966d40?, {0x2a39848?, 0x0?, 0x0?})
        /home/aco/code/flow/flow-cli/internal/cadence/cadence.go:35 +0x35
github.com/spf13/cobra.(*Command).execute(0x2966d40, {0xc00003c050, 0x0, 0x0})
        /home/aco/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:876 +0x67b
github.com/spf13/cobra.(*Command).ExecuteC(0xc00035ef00)
        /home/aco/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:990 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /home/aco/go/pkg/mod/github.com/spf13/cobra@v1.5.0/command.go:918
main.main()
        /home/aco/code/flow/flow-cli/cmd/flow/main.go:82 +0x4f5
```

</details>

<details>
	<summary>Output with the code changes</summary>

```
./flow cadence
Welcome to Cadence v0.26.0!
Type '.help' for assistance.

1> let x = 1
2> let x = 1
error: cannot redeclare constant: `x` is already declared
 --> REPL:1:4
  |
1 |
  |     - previously declared here
  |
2 | let x = 1
  |     ^
3> .exit
```

</details>

### Cause

The issue is caused by const redeclaration, so the error is tied to **two** code lines - the first one declaring the constant, and the other one trying to redeclare it. The `writeCodeExcerpts` method thus contains two excerpts. However, when executing this as part of the REPL, the `code` variable only contains the second, erring code line. The previous line(s) are empty and only added as placeholders (to maintain the line number consistency).

Actual crash happens in the loop handling tabs and spaces with regards to the indicator. First excerpt is referencing a location in the code, but the actual line is empty, so any `line[i]` will crash.

```go
			for i := 0; i < indicatorLength; i++ {
				c := line[i]
				if c != '\t' {
					c = ' '
				}
				p.writeString(string(c))
			}
```

### Other Changes

PR includes a few changes that are not directly related to the crash:

- remove unnecessary indenting spanning almost the entire `for` loop processing an excerpt by inverting the condition (makes the diff seem larger than it actually is - in reality it's indenting/whitespace diff)
- variable renames for (IMO) improved clarity
- omit repeating the indicator character when it's not pointing to an error - I'm not really sure about this on second thought, and perhaps this should be reverted. My original thought was that this looked weird:

```
error: cannot redeclare constant: `const_name` is already declared
 --> REPL:1:4
  |
1 |
  |     ---------- previously declared here
  |
2 | let const_name = 2
  |     ^^^^^^^^^^
```

However, outside of the REPL this is probably not as bad since it will actually underline the relevant part of the code.

- [x] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [ ] ~Updated relevant documentation~
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by turbolent** [comment]
Thank you for looking into this problem. I don't quite remember if and why we prepend empty lines – if that's the case we should maybe address that instead of handling such invalid source code gracefully in the error pretty printer 🤔

**Comment by Maelkum** [comment]
> Thank you for looking into this problem. I don't quite remember if and why we prepend empty lines – if that's the case we should maybe address that instead of handling such invalid source code gracefully in the error pretty printer 🤔

Regarding empty lines - it seems that empty lines are added so that the reference to faulty code (e.g., line 14, column 5) would remain valid.

As for the second party - that's a fair point, I agree. If the REPL code does the work of "composing" the somewhat peculiar version of the source code, it might also have the responsibility of handling the error too, instead of trying to use the error pretty printer that expects valid input.

How do you suggest going about this? Perhaps REPL code should have its own version of the error pretty printer that's a tad more robust/custom tailored for the scenario it's used at.

**Comment by turbolent** [comment]
@Maelkum Thank you again for reporting this bug. I had to re-familiarize myself with why we are prepending empty lines, and then understood what is causing the crash in the error pretty printer (we use the empty-lines code also for error pretty printing, but should use the full code instead there). 

I opened #2021 which fixes the bug in the REPL, and also slightly improves entering invalid code into the REPL in general.
Could you maybe give that a try? If it works, we can maybe merge it and close this PR – given that the error pretty printing is fairly complicated and used on-chain, I'd like to keep it as-is and not add additional code to handle invalid inputs to it. Still, thank you for your effort with this PR, it's much appreciated.

**Comment by Maelkum** [comment]
Hi @turbolent, I've checked out the PR you referenced, and I really like the change. Tested it locally and everything worked. I understand the hesitation of changing a fairly complex piece of code used in a number of scenarios, especially when the culprit code is elsewhere :)

I'll go ahead and close this PR as it's no longer needed. It was fun looking into this after I stumbled upon the crash, got me a chance to familiarize myself with the Cadence source code a bit more. Hopefully I've been of some help :)

Cheers!

**Pull request closed without merging**
