### PR TITLE
mjs build for cadence-parser

### PR DESCRIPTION
**Pull request by nialexsan**
alternative approach for #2815

## Description

cadence-parser's build configuration is using tsc to build a dual package, however, the created esm module cannot be imported from a nodejs es module, as the "type": "module" is missing from the es module specific package.json.

This PR contains a way to solve this issue, although many other ways exist based on the choice of tooling. The solution included is an attempt to fix it with the smallest amount of change to the current toolings and configuration.

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Review by jribbink — APPROVED** [review]
beautiful

**Comment by turbolent** [comment]
Thank you for looking into this and opening an alternative @nialexsan! How does it differ from #2815? What is wrong with approach in the existing PR and how is the approach in this PR better? (Not arguing in any way, just trying to understand)

Could you please also follow and fill out the checklist in the template? Thanks!

**Comment by nialexsan** [comment]
@turbolent this PR implements a generic approach for bundling and it uses a well known tool to do that
a few of the team's concerns regarding #2815 were 
- that it uses [tsconfig-to-dual-package](https://www.npmjs.com/package/tsconfig-to-dual-package) package with only 600 weekly downloads
- having two different `tsconfig.json`s is not a widely acceptable practice, and feels rather hacky

**Comment by turbolent** [comment]
@nialexsan Thank you for the explanation! Agreed that it is preferable to have a single config 👍

**Review by turbolent — APPROVED** [review]

**Pull request merged**
