### PR TITLE
Fixes typo in tutorial

### PR DESCRIPTION
**Pull request by walski**
## Description

Fixes tiny typo
______

- [x] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Review by joshuahannan — APPROVED** [review]
Thank you!

**Comment by walski** [comment]
That benchmark change does look a little unlikely 😂

**Review by SupunS — APPROVED** [review]
Thanks for the fix!

**Comment by SupunS** [comment]
Yup, that looks like a network issue on publishing results. Shouldn't be a blocker for the PR.

**Pull request merged**
