### PR TITLE
Add runtime interface method to receive stats

### PR DESCRIPTION
**Pull request by benjaminkvm**
## Description

While profiling Alan's TXs to determine a reasonable gas limit, I needed a way to expose the gas consumed by interpreted programs (we currently do a check against a limit upon each function invocation, loop iteration etc).

I thought I would make this a bit more generic to support future runtime/interpreter statistics we may want to expose to the Cadence "host" (application implementing the `runtime.Interface`).

Note: 

I realize this is very similar to our `Metrics` system, but (perhaps wrongly) considered that more of a profiling interface and that perhaps there might be merit to exposing certain runtime stats (like gas consumed) via the `runtime.Interface`.

Let me know what you think! Happy to implement via `Metrics`.

### CODE REVIEW

**Comment by benjaminkvm** [comment]
Linter error, hmm..

```
##[error]`interpretion` is a misspelling of `interpreting` (misspell)
  
  ##[error]issues found
```

**Comment by benjaminkvm** [comment]
"Regardless, I don't think gas consumption should be reported in the same place as performance metrics, which are more of an opt-in debugging feature." 💯 

Agree the `runtime.Interface` is getting a bit overwhelming also. Yeah this could be another optional interface the Cadence-host could implement.

**Comment by benjaminkvm** [comment]
Curious for your thoughts on this @turbolent -- think this might be a good time to start breaking out a few methods from the `runtime.Interface`?

**Comment by turbolent** [comment]
Yeah, I definitely agree with splitting the interface up and making some optional.

**Comment by benjaminkvm** [comment]
Going to close this out, active discussions around refactoring out the `runtime.Interface`! This was useful for profiling Cadence gas consumption in either case!

**Pull request closed without merging**
