### PR TITLE
Fix example code from the docs section "design patterns/Script-Accessible report"

### LINKED ISSUE #1713: Documentation provides incorrect code sample
I just started reading the documentation from scratch and noticed this problem: the section [Cadence Design Patterns / Script-Accessible report](https://docs.onflow.org/cadence/design-patterns/#script-accessible-report) provides a sample code with incorrect return. Instead of 

```cadence
// Return the struct with a script
pub fun main(): A.BReport {
    let b: AContract.BResource // Borrow the resource
    let report = b.generateReport()
    return b
}
```
The comment suggests the actual code should be

```cadence
// Return the struct with a script
pub fun main(): A.BReportStruct {
    let b: AContract.BResource // Borrow the resource
    let report = b.generateReport()
    return report
}
```
I would also directly return the response of `b.generateReport` directly instead of assigning it to a variable. 
I can raise a pull request to fix this myself, just need a green light here.

### PR DESCRIPTION
**Pull request by fcostasilva**
Closes #1713 

## Description

The section "design patterns/Script-Accessible report" from the documentation contains an example code with an incorrect return type. This PR fixes this, thus improving its readability.

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Comment by turbolent** [comment]
Thank you for fixing this @fcostasilva! 

Note BTW that #1737 is also fixing this already

**Comment by fcostasilva** [comment]
> Thank you for fixing this @fcostasilva!
> 
> Note BTW that #1737 is also fixing this already

@turbolent Thank you for this quick response. 

> Thank you for fixing this @fcostasilva!
> 
> Note BTW that #1737 is also fixing this already

@turbolent Thank you for the fast response. Then I will let #1737 do the job. Its description doesn't mention any issue, though, maybe some should be referenced there.

**Comment by turbolent** [comment]
@fcostasilva Good point, I'll add a reference to the issue (#1713) 👍

**Comment by turbolent** [comment]
@fcostasilva Your PR still addresses my suggestion in https://github.com/onflow/cadence/pull/1737#discussion_r901954686, so thank you :-)

**Review by turbolent — APPROVED** [review]

**Pull request merged**
