### PR TITLE
Update 02-hello-world.mdx

### PR DESCRIPTION
**Pull request by gnujoow**
Closes #???

## Description

AS-IS
image

Suggested
image

```
Now, all of the public fields, types, and functions defined by that contract
are available within your transaction by using the `ContractName.member` syntax.
```

I suggest modifying the spacing in the code to better understand the explanation that follows the code.

______

- [x] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation 
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Comment by joshuahannan** [comment]
I'm a little bit confused by what you're suggesting here. Can you elaborate? Thanks! 😃

**Comment by gnujoow** [comment]
thanks for your comment @joshuahannan.

in real-world code, import package with spacing occurs syntax error. And in the following document says **your transaction by using the `ContractName.member` syntax.** So I think to make `Contract Name` into camelCase is easier to understand to javascript developers.

**Review by joshuahannan — APPROVED** [review]
OH, I see! I looked at it a bunch of times before and didn't notice the difference, but I see now. This makes sense. Thank you!

**Review by turbolent — APPROVED** [review]
Thank you!

**Pull request merged**
