### PR TITLE
Add wasm generation for docgen tool

### PR DESCRIPTION
**Pull request by SupunS**
______

- [ ] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by turbolent** [comment]
😍

**Review by turbolent — APPROVED** [review]
Nice! We should also create and publish an NPM package for it, see `npm-packages`, e.g. just like for the parser

**Comment by SupunS** [comment]
@turbolent Added the NPM package in separate PR: https://github.com/onflow/cadence/pull/1008

**Comment by turbolent** [comment]
@SupunS Thanks for adding the PR!

**Pull request merged**
