### PR TITLE
Storagemap backport

### PR DESCRIPTION
**Pull request by dsainati1**
This is a backport of https://github.com/onflow/cadence/pull/1248 and https://github.com/onflow/cadence/pull/1391  in order to make it possible to perform a storage migration on Flow. 

______

- [ ] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Review by turbolent — COMMENTED** [review]
Good idea to untangle this piece 👍 

I assume that this is literally just re-applying the commits on top of v0.21? Were there any conflicts?

**Comment by dsainati1** [comment]
> I assume that this is literally just re-applying the commits on top of v0.21? Were there any conflicts?

Yes; there were a couple of conflicts, but it was fairly self-evident what the solution was (mostly just code that had been modified in one commit and a function that had been renamed in the other).

**Review by turbolent — COMMENTED** [review]
I diffed the patch of #1248 and this PR's patch, and it looks good 👍 

Given that this change requires a storage migration, maybe it is better to release it as v0.22. Could you please create a new branch `v0.22` branching from `v0.21`, and re-target this PR to it?

**Comment by turbolent** [comment]
@dsainati1 Thank you! I think merging v0.22 into this PR should fix CI

**Review by turbolent — APPROVED** [review]

**Pull request merged**
