### PR TITLE
Add migration report for aug 7

### PR DESCRIPTION
**Pull request by zhangchiqing**

### CODE REVIEW

**Review by j1010001 — APPROVED** [review]

**Comment by bluesign** [comment]
> Stats: 745 contracts staged, 702 successfully upgraded, 43 failed to upgrade (4 failed with FiatToken)

not sure if this is correct.

**Review by SupunS — APPROVED** [review]

**Comment by SupunS** [comment]
@bluesign 
> not sure if this is correct.

Why do you think so? The number seems consistent with the previous stats 🤔

**Comment by bluesign** [comment]
@SupunS hmm I compared with my staging.dnz.dev ( then I searched for  ✅ in .md file )

**Comment by SupunS** [comment]
oh I see. I'll see why the numbers are different. Thanks for flagging!

**Comment by j1010001** [comment]
I checked again and @bluesign is right, I can see 797 staged, 41 errors, 756 successfuly migrated. I'll update the report

**Pull request merged**
