### PR TITLE
Add support for dereferencing optional references

### LINKED ISSUE #3005: Lift `*` to optional references
### Issue to be solved

As mentioned in https://github.com/onflow/cadence/pull/2982, it would be nice for the newly introduced `*` dereference operator to implicitly lift to optional references. I.e., assuming the `*` operator has type `fun<T: Primitive>(_ ref: &T): T`, we should implicitly overload the operator to also have type `fun<T: Primitive>(_ ref: &T?): T?`.

### Suggested Solution

_No response_

### PR DESCRIPTION
**Pull request by turbolent**
Closes #3005 

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by dsainati1** [comment]
Does this only unwrap optionals one layer? I.e. will `*` fail on a `&Int??`

**Comment by turbolent** [comment]
@dsainati1 
> Does this only unwrap optionals one layer? I.e. will `*` fail on a `&Int??`

Yes, only one layer of optionality is unwrapped, just like the optional chaining version did. This is also similar to how e.g. `!` behaves. `*` on `&Int??` won't fail, but result in `Int?`.

**Comment by dsainati1** [comment]
Yeah, that makes sense. 

> To be honest, this is already quite some syntactic sugar, maybe we shouldn't even have this?

IMO this is useful for the same reason that optional chaining is; it makes a common case more convenient to use. You're right that this is doable another way, but it would probably be more frustrating to do that way. The same is true for optional chaining!

I'm happy with this only unwrapping one layer of the optional.

**Review by dsainati1 — APPROVED** [review]

**Comment by turbolent** [comment]
> IMO this is useful for the same reason that optional chaining is; it makes a common case more convenient to use.

Good point, agreed!

**Pull request merged**
