### PR TITLE
Refactor memory-metering interface API

### PR DESCRIPTION
**Pull request by SupunS**
Work towards https://github.com/dapperlabs/cadence-private-issues/issues/2

## Description

Refactor the memory-metering interface API to be in-lined with the computation metering API.

old-signature:
```go
UseMemory(usage MemoryUsage)
```
new-signature:
```go
MeterMemory(usage common.MemoryUsage) error
```
Returned `error` is handled by Cadence.
______

- [ ] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Review by janezpodhostnik — APPROVED** [review]
The changes look good, but my question is if the `MeterMemory` function should accept two parameters like `MeterComputation(operationType common.ComputationKind, intensity uint) error` does.

**Comment by SupunS** [comment]
That's a good question! I had the same thought when adding changes. The reason why I went with the single `common.MemoryUsage` parameter is, in future if we needed to pass more properties through this API, by having this wrapper object (`common.MemoryUsage`) we can seamlessly add them, without changing/breaking the API.

**Comment by janezpodhostnik** [comment]
That is true, but if the `common.MemoryUsage` changes, wouldn't that still be a breaking change for anyone implementing the runtime interface.

**Comment by SupunS** [comment]
Additions of fields would be backward compatible. Yes, they would have to update the code to use the new field, but the code will continue to compile without any changes.

**Review by turbolent — APPROVED** [review]

**Review by ramtinms — APPROVED** [review]

**Pull request merged**
