### PR TITLE
Port fixes of v0.42.8-patch.4

### LINKED ISSUE #3081: Fixes of v0.42.8-patch.4 do not work on master
### Current Behavior

The fixes of v0.42.8-patch.4 work well on v0.42 (https://github.com/onflow/cadence/pull/3076), but they don't work fully on master: https://github.com/onflow/cadence/pull/3079

### Expected Behavior

All tests should pass

### Steps To Reproduce

Run tests on WIP PR branch #3079

### Environment

```markdown
- Cadence version:
- Network:
```

### PR DESCRIPTION
**Pull request by turbolent**
Closes #3081

## Description

Port of #3076 to `master`

Had to make some adjustments to make the fixes and tests compatible with Cadence 1.0 in d62622767ad85c729893a1d2dcc0c26abecdf979
 
______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by SupunS** [comment]
@turbolent I guess we still need this PR? I can have a look to see why the tests are failing

**Comment by SupunS** [comment]
Additional changes made for fixing the code/test:
- [Check for invalidated resource in expression getter-setter](https://github.com/onflow/cadence/pull/3079/commits/68f0aa56167997de09810123e308fbe913d0631b)
- [Convert references based on borrow type](https://github.com/onflow/cadence/pull/3079/commits/0077f057bb74170b6de7fc1e088a7e1854d86ee8)
- [Temporarily disable TestResourceLossViaSelfRugPull](https://github.com/onflow/cadence/pull/3079/commits/fbbe6bc3df02123ef04c8a49ce9e1f679843efad)

**Review by turbolent — COMMENTED** [review]
Can't approve my own PR, but your changes look good @SupunS! Nice work! 👏

**Review by dsainati1 — APPROVED** [review]

**Comment by SupunS** [comment]
Yup, https://github.com/dapperlabs/cadence-internal/issues/192.
This is not for the skipped test itself, but rather for the original issue

**Pull request merged**
