### PR TITLE
Add limit on call stack depth

### PR DESCRIPTION
**Pull request by SupunS**
## Description

Porting https://github.com/dapperlabs/cadence-internal/pull/32

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by turbolent** [comment]
Even though it turned out that the call stack depth wasn't the real problem we saw on Testnet, it might be still useful to have this as a feature. Maybe we can merge it and disable it for now?

**Comment by SupunS** [comment]
Yeah, that was my feeling as well. It is good to enforce it from the language in a first-class manner. 

What if we still keep it, but with a slightly higher value? (e.g: 2000)

**Comment by turbolent** [comment]
Yes, I think it's good to merge, and agreed 2000 should be OK. I tagged it as a breaking change, because we should flag this change of behaviour to users/developers

**Review by turbolent — APPROVED** [review]

**Comment by turbolent** [comment]
It would be good to make this limit configurable, like the computation limit (but in a separate PR)

**Pull request merged**
