### PR TITLE
Add 'isValid' field to PublicKey

### PR DESCRIPTION
**Pull request by SupunS**
## Description

Work towards #582

______

For contributor use:

- [ ] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Review by turbolent — COMMENTED** [review]
Looks good! 

Just have one concern regarding naming here: https://github.com/onflow/cadence/pull/837#discussion_r620665339

**Comment by tarakby** [comment]
Same in this PR and #837, I reviewed the general APIs and Go syntax, but I don't quite understand how runtime works. I suggest we sync at some point to make sure we're aligned on the features.

**Comment by SupunS** [comment]
Thanks, @turbolent ad @tarakby for the reviews. Changed the name of the field to `isValid` in 4c619ba, as discussed.

**Review by turbolent — APPROVED** [review]
Nice! 👍

**Pull request merged**
