### PR TITLE
Run compatibility checker for PRs

### PR DESCRIPTION
**Pull request by SupunS**
## Description

Runs the checker for every PR targeted at the `master` branch and `v**` branches.

______

- [x] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by dsainati1** [comment]
Can we extend this to any `feature/` branch PRs that aren't targeting `feature/stable-cadence` specifically?

**Comment by SupunS** [comment]
I didn't add `feature/**` branches because we might also develop breaking changes (large features in particular) in their own feature branches, other than the stable-cadence branch.
Such branches would get checked when they are going to get merged into the master anyway.

**Review by turbolent — APPROVED** [review]
Nice!

**Comment by turbolent** [comment]
@SupunS maybe add that reasoning as a comment to the branch patterns in the YAML

**Review by dreamsmasher — APPROVED** [review]

**Pull request merged**
