### PR TITLE
Function types carry information about their access modifier

### PR DESCRIPTION
**Pull request by dsainati1**
Necessary for the implementation of https://github.com/onflow/cadence/issues/2918

______

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation 
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Comment by dsainati1** [comment]
In order to determine the entitlements that the runtime values for `self` and `base` will need inside of a function invocation, we need to know what access that function was defined with. `FunctionValue` carries a `FunctionType`, which after this change would carry an `Access`, so we would be able to figure out what authorization to create the `self` and `base` references with.

**Comment by turbolent** [comment]
For example, argument labels are not declared on the function type either, but are part of the variable and member, and checked at call-sites. Is the access of variables and member not sufficient here?

**Comment by dsainati1** [comment]
This is not necessary for type checking, no. This is for the interpreter. If I have some attachment definition:

```
attachment A for R {
    access(E) fun foo() {}
}
```

When we interpret an expression `a.foo()` for some reference to `A`, we need to know what the appropriate entitlements are that we need to provide to the `self` and `base` references that we create inside of the body of `foo`, and we need information about `foo`'s access modifier in order to do that.

**Comment by turbolent** [comment]
@dsainati1 Let's maybe sync on this tomorrow, it might be easier to clarify this in a call

**Pull request closed without merging**
