### PR TITLE
Moving comp metering to FVM v0.23 port

### PR DESCRIPTION
**Pull request by janezpodhostnik**
## Description

Port of [Moving computation metering and limit enforcement responsibility to the environment](https://github.com/onflow/cadence/pull/1469) to v0.23

One change was made: we only meter 	`ComputationKindStatement`, `ComputationKindLoop` and `ComputationKindFunctionInvocation`.

______

- [ ] Targeted PR against `master` branch
- [ ] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation 
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [ ] Added appropriate labels

### CODE REVIEW

**Review by dsainati1 — APPROVED** [review]

**Comment by turbolent** [comment]
Thank you for the backport PR!

It would be great to keep the semantic commits that were pushed in the original PR. Could you please push the PR's commits instead of a single squashed new one?

I wrote up here how it can be easily done using GitHub's PR patch feature: https://github.com/onflow/cadence/pull/1443#issuecomment-1050396324

**Review by turbolent — APPROVED** [review]

**Comment by turbolent** [comment]
@janezpodhostnik Looks good! What is the reason for 00b19e27438f114772e86eabf2431a3a3d7af311 ?

**Comment by janezpodhostnik** [comment]
Only ComputationKindStatement, ComputationKindLoop and ComputationKindFunctionInvocation are needed for now, as those are the same as the previously metered computation.

I could also remove 00b19e2 and just ignore other computation kinds in the FVM. (or maybe even include them in the model... hmmm)

Since this is a back port I wanted to reduce its footprint to what is needed, but now I'm not so sure that is the best option anymore.

**Comment by janezpodhostnik** [comment]
@turbolent I removed 00b19e2.

**Review by turbolent — APPROVED** [review]
Looks good, thank you!

**Comment by ramtinms** [comment]
Yeah I kept them intentionally, with the plan to ignore them and log them on the FVM side, we should keep the changes.

**Comment by turbolent** [comment]
Looks like the commits were then still squashed 🙈 

It's usually easier to track down bugs when we have smaller, semantic commits

**Pull request merged**
