### PR TITLE
Add native function declarations for all relevant `Test` contract functions

### PR DESCRIPTION
**Pull request by m-Peter**
Closes https://github.com/onflow/cadence/issues/2822

## Description

With the introduction of https://github.com/onflow/cadence/pull/2821, we can now declare native functions inside the `Test` contract, and remove the workaround that used `CompositeType.ResolveMembers()`.
______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [x] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [x] Updated relevant documentation 
- [x] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Comment by m-Peter** [comment]
I am still getting some checking errors for native function declarations with type parameters, e.g.:
```shell
panic: Checking failed:
error: cannot find type in this scope: `T`
   --> Test:445:50
```
The relevant function declaration is:
```cadence
/// Creates a matcher with a test function.
/// The test function is of type '((T): Bool)',
/// where 'T' is bound to 'AnyStruct'.
///
access(all)
native fun newMatcher<T: AnyStruct>(_ test: ((T): Bool)): Test.Matcher {}
```
To my knowledge, I have updated the relevant `parser.Config` & `sema.Config` usages:
```go
parser.Config{
	NativeModifierEnabled: true,
	TypeParametersEnabled: true,
}

&sema.Config{
	BaseValueActivation:     activation,
	AccessCheckMode:         sema.AccessCheckModeStrict,
	AllowNativeDeclarations: true,
}
```

What could be the root cause of this checking error? :thinking:

**Comment by SupunS** [comment]
Can you maybe rebase the PR on top of https://github.com/onflow/cadence/pull/2850, and see if this is now solved?

**Comment by m-Peter** [comment]
Hey @SupunS,

I have rebased on top of master, and indeed the checking error regarding type parameters is solved. However, I hit another roadblock in this commit https://github.com/onflow/cadence/pull/2823/commits/6eb4de7775a637d80becec7e295c7cc1a3bef29d. Basically, we have two functions with arity (`Test.assert` & `Test.fail`):
```go
// `message` parameter is optional
Arity: &sema.Arity{Min: 1, Max: 2},
```
Which is not possible to somehow defined with `native` declarations. Related discord thread: https://discord.com/channels/613813861610684416/1159499730573860895/1159806153862172712

**Comment by m-Peter** [comment]
Closing this in favor of https://github.com/onflow/cadence/pull/2926

**Pull request closed without merging**
