### PR TITLE
Cadence Style Guide

### PR DESCRIPTION
**Pull request by alilloig**
Closes [#960](https://github.com/onflow/flow/issues/960)
## Description
Developers need better guidelines for how to write clean cadence code. Define those guidelines at `docs/cadence-style-guide.md`. Early PR containing only table of contents to seek consensus about which points should the guide contain and check everyone's thoughts on conflictive aspects.

______

- [x] Targeted PR against `master` branch
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work
- [ ] Code follows the [standards mentioned here](https://github.com/onflow/cadence/blob/master/CONTRIBUTING.md#styleguides)
- [ ] Updated relevant documentation 
- [ ] Re-reviewed `Files changed` in the Github PR explorer
- [x] Added appropriate labels

### CODE REVIEW

**Review by joshuahannan — COMMENTED** [review]
Looks good so far! Maybe we can also add a section for access control modifier naming? `access(self)` and `priv` currently mean the same thing, as does `access(all)` and `pub`, so we could give recommendations about that

**Comment by alilloig** [comment]
> Looks good so far! Maybe we can also add a section for access control modifier naming? `access(self)` and `priv` currently mean the same thing, as does `access(all)` and `pub`, so we could give recommendations about that

Yeah that makes a lot of sense! I´m prone to access(self) and pub.

**Comment by turbolent** [comment]
Great idea to start on this! I have a lot of thoughts :-) 

I would recommend proposing this as a FLIP, so everyone can chime in

**Comment by turbolent** [comment]
Some pointers:
- [Swift API Design Guidelines](https://www.swift.org/documentation/api-design-guidelines/)
- [Google's Swift Style Guide](https://google.github.io/swift/)
- [Kotlin Coding Conventions](https://kotlinlang.org/docs/coding-conventions.html)
- [Rust Style Guidelines](https://doc.rust-lang.org/1.0.0/style/)

**Comment by alilloig** [comment]
Great thank you!! I was randomly looking at the Go style guide or the airbnb js style guide for instance

**Comment by joshuahannan** [comment]
@turbolent Why do you think this needs to be a FLIP? It isn't a new big feature or anything. Couldn't the discussion just happen in this issue or in a PR?

**Comment by turbolent** [comment]
As far as I understand, this guideline is going to recommend a certain style to be the "preferred" ("correct?") style, which will then also have implications for tooling, e.g. the code formatter should probably generate code in that style.

It is a good idea to involve the community and ask for feedback.

For example, [Rust even has a "meta RFC" for the *process* of proposing style guide changes](https://rust-lang.github.io/rfcs/1607-style-rfcs.html).

**Comment by bluesign** [comment]
This is a great initiative. I also think this can be FLIP, though I am in more favour of having it's on repository. 

Problem with this being FLIP is, this feels like ruleset, and discussing different rules in a single place will not be enough. If we make this a repo: 

- We can create issues for questions, where they can be answered. 
- We can create PRs for proposals, where they can be discussed separately and merged or closed. 

Also I think this can be good place for ideas to grow for extending Cadence standard library or fix common problems with the wrong usage of the language. For example: when I last reviewed some contracts for community, I figured out there are very common misconceptions, but couldn't find a place to put those as feedback.

**Comment by pgebheim** [comment]
I agree with @bluesign  -- a FLIP should be seen as a repository of technical standards or governance actions, which provide clear reasonsing, argumentation, transparency, and history for decision making and consensus.

A style guide is inherently a guide and doesnt actually define interoperability standards.

As such, I think this makes sense as its own repo and can be the schelling point for where people start, but I would expect this guide to be forked depending upon the audience over time.

**Comment by turbolent** [comment]
I wasn't suggesting that the style guide should become part of the specification, but once it is in the Cadence repo, it might be seen as such. In any case, we should make sure to make this clear.

My main point was that we already have a process for proposals to Flow, FLIPs, and we should use it instead of having an ad-hoc discussion in this PR.  

> FLIP should be seen as a repository of technical standards or governance actions, which provide clear reasoning, argumentation, transparency, and history for decision making and consensus.
> A style guide is inherently a guide and doesn't actually define interoperability standards.

I don't think we ever said anywhere that FLIPs are just for technical/interoperability standards and governance actions, I always just saw them as a means of having a process for any kind of proposal, with the main benefits being the ones you stated @pgebheim (reasoning, consensus, etc.). 

If a FLIP isn't the right place, then by all means we can also have the same discussion here.

**Comment by bluesign** [comment]
@turbolent My comment was more about discussing many unrelated items in a single FLIP ( or single issue ) is not being productive. 

Neither FLIP nor single issue is good for discussing totally unrelated rules in a ruleset. But also they are too related to separate into different FLIPs. 

My proposal was to make style guide a separate repository. So each item can be discussed around issues or PRs. 

Also I think this can be little more expanded into best practices ( not stuck in style only )

**Comment by alilloig** [comment]
I also really like the idea of having a repo for gathering all cadence best practices. Structuring the discussion around each point in one PR/issue also makes a lot of sense!! Even if we are not strictly just talking about the code style guide on the repo the `cadence-style-guide` name seems right to me.

**Comment by turbolent** [comment]
I haven't yet, please do, that would be much appreciated! 👍

**Comment by alilloig** [comment]
do we all feel good with `cadence-style-guide` as the repo name?

**Pull request closed without merging**
